---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-virtualservice-merger
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ctrl-stack
  name: istio-virtualservice-merger
---
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-virtualservice-merger-leader-election-role
  namespace: ctrl-stack
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-virtualservice-merger-leader-election-rolebinding
  namespace: ctrl-stack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-virtualservice-merger-leader-election-role
subjects:
  - kind: ServiceAccount
    name: istio-virtualservice-merger
    namespace: ctrl-stack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-virtualservice-merger-manager-role
rules:
  - apiGroups:
      - istiomerger.monime.sl
    resources:
      - virtualservicemerges
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - istiomerger.monime.sl
    resources:
      - virtualservicemerges/status
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
    verbs:
      - '*'
  - apiGroups:
      - ""
      - apps
      - batch
      - policy
      - extensions
    resources:
      - jobs
      - pods
      - events
      - secrets
      - services
      - configmaps
      - statefulsets
      - poddisruptionbudgets
      - persistentvolumeclaims
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-virtualservice-merger-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-virtualservice-merger-manager-role
subjects:
  - kind: ServiceAccount
    name: istio-virtualservice-merger
    namespace: ctrl-stack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-virtualservice-merger
  namespace: ctrl-stack
  labels:
    app: istio-virtualservice-merger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-virtualservice-merger
  template:
    metadata:
      labels:
        app: istio-virtualservice-merger
    spec:
      containers:
        - name: operator
          image: ghcr.io/splashtopinc/virtualservice-operator
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: LEADER_ELECTION_NAMESPACE
              value: ctrl-stack
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
      serviceAccountName: istio-virtualservice-merger
      imagePullSecrets:
        - name: ghcr-repo-key
